print("введите 1-ый список")
spisok1 = list(map(int, input().split()))
print("введите 2-ой список")
spisok2 = list(map(int, input().split()))
print("первый список-", spisok1)
print("второй список-", spisok2)
set1 = set(spisok1)
set2 = set(spisok2)
print(f"соответствующие множества:\n {set1}\n {set2}")
set3 = set1.intersection(set2)
summa = sum(set3)
print("сумма общих членов списка", summa)